name: omni
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12

  - ipykernel==6.29.5

  - conda-forge::pytorch==2.7.0
  - conda-forge::torchvision==0.22.0
  - conda-forge::pytorch-gpu==2.7.0

  - pip:
    # conflicting dependencies
    # - -r ./OmniParser/requirements.txt
    - -r ./requirements.txt
