ARG OMNI_TAG=v1.5.0


FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

ARG OMNI_TAG

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
        python3-pip python3-venv \
        libgl1 \
        libsm6 \
        libxext6 \
        libglib2.0-0 \
        libxrender-dev \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip3 install --upgrade pip

RUN git clone -b ${OMNI_TAG} https://gh-proxy.com/https://github.com/microsoft/OmniParser.git /app
RUN pip3 install --no-cache-dir \
    torch==2.7.0 torchvision==0.22.0 \
    --index-url https://download.pytorch.org/whl/cu126
RUN pip3 install --no-cache-dir \
    easyocr==1.7.2 \
    supervision==0.18.0 \
    openai==1.3.5 \
    # fix https://github.com/microsoft/OmniParser/issues/312
    transformers==4.51.1 \
    # fix https://github.com/microsoft/OmniParser/issues/104
    ultralytics==8.3.161 \
    azure-identity==1.23.0 \
    numpy==2.3.1 \
    opencv-python==4.11.0.86 \
    opencv-python-headless==4.11.0.86 \
    gradio==5.35.0 \
    dill==0.4.0 \
    accelerate==1.8.1 \
    timm==1.0.16 \
    einops==0.8.0 \
    paddlepaddle==3.1.0 \
    paddleocr==2.10.0 \
    dill==0.4.0 \
    accelerate==1.8.1 \
    timm==1.0.16 \
    einops==0.8.0 \
    paddlepaddle==3.1.0 \
    paddleocr==2.10.0

EXPOSE 8501

VOLUME /root/.cache
VOLUME /root/.EasyOCR
VOLUME /root/.paddleocr
VOLUME /app/weights

CMD ["python", "gradio_demo.py", "--icon_detect_model", "/app/weights/icon_detect_v1_5/model_v1_5.pt", "--icon_caption_model", "florence2"]
