

services:
  omni_app:
    image: xiaoyao9184/omni:ba4e04fc
    container_name: omni_gradio
    command: bash -c "python weights/convert_safetensor_to_pt.py --version v1 && python gradio_demo.py"
    environment:
      - TORCH_DEVICE=cuda
    ports:
      - "7861:7861"
    volumes:
      - ./../../OmniParser/weights/icon_detect:/app/weights/icon_detect
      - ./../../OmniParser/weights/icon_caption_florence:/app/weights/icon_caption_florence
      - ./../../cache/.EasyOCR:/root/.EasyOCR
      - ./../../cache:/root/.cache
      - ./../../imgs:/app/imgs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
