
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./OmniParser /app
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8501

VOLUME /root/.cache

CMD ["python", "gradio_demo.py"]
