# ARG OMNI_VERSION=0.0.0


# FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

# ARG OMNI_VERSION

# WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     python3-pip \
#     libgl1-mesa-glx \
#     libsm6 \
#     libxext6 \
#     libglib2.0-0 \
#     libxrender-dev \
#     && rm -rf /var/lib/apt/lists/*

# RUN pip3 install --upgrade pip

# RUN pip3 install --no-cache-dir omni==${OMNI_VERSION}

# EXPOSE 8501

# VOLUME /root/.cache

# CMD ["python", "gradio_demo.py"]
