

services:
  omni_app:
    image: xiaoyao9184/omni:1.5.0
    container_name: omni_gradio
    environment:
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
    ports:
      - "7861:7861"
    volumes:
      - ./../../OmniParser/weights:/app/weights
      - ./../../cache/.EasyOCR:/root/.EasyOCR
      - ./../../cache/.paddleocr:/root/.paddleocr
      - ./../../cache:/root/.cache
      - ./../../imgs:/app/imgs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
